name: 🚀 Deploy on master

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 🚚  Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.16.1"
      - name: 🎉 npm install and build
        run: |
          npm install
          npm run build
        env:
          GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      - name: 📂 deploy to main repository
        run: |
          cd out
          touch .nojekyll
          git config --global user.email ""
          git config --global user.name "GithubAction"
          git init
          git remote add stspcsr_host https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/raisehead-studio/stspcsr_host.git
          git add -A
          git commit -m 'deploy with Github Action'
          git push -f stspcsr_host master:gh-pages
